(function() {var implementors = {};
implementors['void'] = [];implementors['libc'] = [];implementors['nix'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='nix/fcntl/struct.flock.html' title='nix::fcntl::flock'>flock</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='nix/sys/quota/quota/struct.QuotaValidFlags.html' title='nix::sys::quota::quota::QuotaValidFlags'>QuotaValidFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='nix/sys/quota/quota/struct.Dqblk.html' title='nix::sys::quota::quota::Dqblk'>Dqblk</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='nix/sys/statvfs/vfs/struct.FsFlags.html' title='nix::sys::statvfs::vfs::FsFlags'>FsFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='nix/sys/statvfs/vfs/struct.Statvfs.html' title='nix::sys::statvfs::vfs::Statvfs'>Statvfs</a>",];implementors['mio'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='mio/struct.EventLoopConfig.html' title='mio::EventLoopConfig'>EventLoopConfig</a>",];implementors['rotor'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='rotor/mio/struct.EventLoopConfig.html' title='rotor::mio::EventLoopConfig'>EventLoopConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='rotor/struct.Config.html' title='rotor::Config'>Config</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
